# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Generate Difference'
        run: |
           LATEST_STABLE_TAG=`git tag  -l danone-def-v*  --sort=taggerdate | tail -n1`
           echo Last Stable Tag
           echo $LATEST_STABLE_TAG
           CURRENT_COMMIT_ID=`git rev-parse --verify HEAD`
           echo Current Commit ID
           echo $CURRENT_COMMIT_ID
